### ISSUE TITLE
Information about the capture

### ISSUE THREAD

**Issue by mcbuehler** [CrisalixSA/h3ds#10]
Could you provide some more information on how the capture was conducted? 

- What kind of camera was used for the color images?
- Are the images multiview or captured sequentially?
- If the latter: How was the camera was moved around the head? Could it be that the head was moving during a capture?

Thank you!

**Comment by gilTriginer** [comment]
Sure! Let me address your questions specifically, but you can also find more information about the data acquisition setup in the supplementary information of our paper [H3D-Net: Few-shot high-fidelity 3D head reconstruction](https://openaccess.thecvf.com/content/ICCV2021/html/Ramon_H3D-Net_Few-Shot_High-Fidelity_3D_Head_Reconstruction_ICCV_2021_paper.html)

The color images where taken using the camera of a hand-held ipad pro (2nd generation), on top of which we mounted a structured light sensor to do SLAM and obtain relative cameras. As you suggest, the subject moved during the capture process. The recording sequence was the following: the camera started at a frontal pose, and moved up and down to capture the subject from above and below. From here on, the camera stayed still and the subject was rotated. This arrangement was necessary due to the limited range of movement of the high-resolution 3D scanner we were using. Admittedly, this also caused some inconveniences, such as inconstant lighting of the scene, and (quite small) non-rigid deformations of the subject across frames.

**Comment by mcbuehler** [comment]
Thank you, this is very helpful!
